language: node_js
node_js:
  - "8"
python:
  - 3.6.3

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot --base-href="/admin" --deploy-url="/admin"

before_deploy:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin

deploy:
  - provider: script
    script: aws s3 sync ./dist s3://revolutionuc.com/admin --region=us-east-2 --delete
    skip_cleanup: true

notifications:
  email: false
