language: node_js
node_js:
  - "8"
python:
  - 3.6.3

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot

  before_deploy:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

deploy:
  - provider: script
    script: aws s3 sync ./dist s3://test.revolutionuc.com/admin --region=us-east-2 --delete
    skip_cleanup: true
    on:
      branch: master
